//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tartuga_Simonov.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public decimal TotalCost { get; set; }
        public Nullable<int> BakeryID { get; set; }
        public Nullable<int> FastFoodID { get; set; }
        public Nullable<int> SaladID { get; set; }
        public Nullable<int> BeverageID { get; set; }
        public int TableID { get; set; }
    
        public virtual Bakery Bakery { get; set; }
        public virtual Beverage Beverage { get; set; }
        public virtual FastFood FastFood { get; set; }
        public virtual Salad Salad { get; set; }
        public virtual Table Table { get; set; }
    }
}
