//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tartuga_Simonov.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.BakeryOrder = new HashSet<BakeryOrder>();
            this.BeverageOrder = new HashSet<BeverageOrder>();
            this.FastFoodOrder = new HashSet<FastFoodOrder>();
            this.SaladOrder = new HashSet<SaladOrder>();
        }
    
        public int ID { get; set; }
        public decimal TotalCost { get; set; }
        public Nullable<int> BakeryID { get; set; }
        public Nullable<int> FastFoodID { get; set; }
        public Nullable<int> SaladID { get; set; }
        public Nullable<int> BeverageID { get; set; }
        public int TableID { get; set; }
        public string Qry { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BakeryOrder> BakeryOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeverageOrder> BeverageOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FastFoodOrder> FastFoodOrder { get; set; }
        public virtual Table Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaladOrder> SaladOrder { get; set; }
    }
}
